# Generated by Django 5.1 on 2024-10-04 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='blance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.BigIntegerField(default=0)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blance', to='home.idcard')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.BigIntegerField()),
                ('DTime', models.DateTimeField()),
                ('FromUser', models.CharField(blank=True, max_length=1000, null=True)),
                ('Source', models.CharField(blank=True, max_length=1000, null=True)),
                ('comments', models.CharField(blank=True, max_length=10000, null=True)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Income', to='home.idcard')),
            ],
        ),
        migrations.CreateModel(
            name='Outgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.BigIntegerField()),
                ('DTime', models.DateTimeField()),
                ('ToUser', models.CharField(blank=True, max_length=1000, null=True)),
                ('Where', models.CharField(blank=True, max_length=1000, null=True)),
                ('Why', models.CharField(blank=True, max_length=10000, null=True)),
                ('comments', models.CharField(blank=True, max_length=10000, null=True)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Outgo', to='home.idcard')),
            ],
        ),
        migrations.DeleteModel(
            name='logs',
        ),
    ]
