# Generated by Django 5.1 on 2024-10-04 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blance_income_outgo_delete_logs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Income', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outgo',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Outgo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='blance',
        ),
    ]
