# Generated by Django 5.1 on 2024-10-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_income_userid_alter_outgo_userid_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='outgo',
            old_name='userID',
            new_name='user',
        ),
    ]
