# Generated by Django 5.1 on 2024-10-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_userid_income_user_rename_userid_outgo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outgo',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
