# Generated by Django 5.1 on 2024-10-05 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_loan_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='payment_date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2024, 10, 5, 6, 34, 35, 534009)),
            preserve_default=False,
        ),
    ]
