# Generated by Django 5.1 on 2024-10-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_loan_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='last_date',
        ),
    ]
