# Generated by Django 5.1 on 2024-10-05 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_balance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='payment_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
